// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return android;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyA8AqB3YNKws5jP9BAuMxaqQSEANTas56M',
  //   appId: '1:649831649414:web:b68c0e65f599000da88107',
  //   messagingSenderId: '649831649414',
  //   projectId: 'ujikom-16a31',
  //   authDomain: 'ujikom-16a31.firebaseapp.com',
  //   databaseURL: 'https://ujikom-16a31-default-rtdb.asia-southeast1.firebasedatabase.app',
  //   storageBucket: 'ujikom-16a31.appspot.com',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'IzaSyBGEfjgc9jWwoAlYQcbgz0CrBjEj9teD2c',
    appId: '1:597838926231:android:e0463fc92f84579840b4d2',
    messagingSenderId: '597838926231',
    projectId: 'ininyobaja',
    databaseURL:
        'https://ininyobaja-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ininyobaja.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBP9UFS8D5e3aZD0g3WaZ6aCuCXybXUTeo',
  //   appId: '1:649831649414:ios:dc3ed047b5219714a88107',
  //   messagingSenderId: '649831649414',
  //   projectId: 'ujikom-16a31',
  //   databaseURL: 'https://ujikom-16a31-default-rtdb.asia-southeast1.firebasedatabase.app',
  //   storageBucket: 'ujikom-16a31.appspot.com',
  //   iosClientId: '649831649414-mso2819iulq4701sd4i2704aus13p63f.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.ujikom',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyBP9UFS8D5e3aZD0g3WaZ6aCuCXybXUTeo',
  //   appId: '1:649831649414:ios:dc3ed047b5219714a88107',
  //   messagingSenderId: '649831649414',
  //   projectId: 'ujikom-16a31',
  //   databaseURL: 'https://ujikom-16a31-default-rtdb.asia-southeast1.firebasedatabase.app',
  //   storageBucket: 'ujikom-16a31.appspot.com',
  //   iosClientId: '649831649414-mso2819iulq4701sd4i2704aus13p63f.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.ujikom',
  // );
}
